
<div class="footer">
<div class="right">
<p>&copy; 2005 GHNS Developers</p>
<!--
<p><a href="http://validator.w3.org/check/referer">Validate XHTML 1.0 Strict</a></p>
-->
<a href="http://developer.berlios.de" title="BerliOS Developer"> <img src="http://developer.berlios.de/bslogo.php?group_id=3952" width="124px" height="32px" border="0" alt="BerliOS Developer Logo"></a>
</div>
<p>Email to the <a href="mailto:ghns-discuss@lists.berlios.de">mailing list</a></p>
<p>Photo Credit: Dimiter Tzankov, <a href="http://www.sxc.hu/">stock.xchng</a></p>
<p>Webdesign Credit: <a href="http://www.oswd.org/userinfo.phtml?user=ad_267">ad_267</a></p>
</div>

</div>
</body>
</html>
