<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>GHNS Project - Get Hot New Stuff!</title>
<link rel="stylesheet" type="text/css" href="/screenstyle.css" />
</head>
<body>
<div class="container">

<div class="titleblock">
<h1>GHNS Project</h1>
<p>&ldquo;Get Hot New Stuff!&rdquo;</p>
</div>

<div>
<ul class="navbar">
<li><a href="/" class="nav">Home</a></li>
<li><a href="/software.php" class="nav">Specs & Software</a></li>
<li><a href="/sites.php" class="nav">GHNS Sites</a></li>
<li><a href="/contact.php" class="nav">Contact</a></li>
</ul>
</div>

